---
name: CI

on:
  push:
    branches: [ main ]
    paths:
    - 'infrastructure/**'
    - '.github/workflows/package.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Set the AWS credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: package sam template
      uses: advancedcsg-open/action-aws-sam@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: package --template-file infrastructure/ec2-stack.yml --output-template-file infrastructure/ec2-stack.template --s3-bucket s3artifactdemohemanth --s3-prefix demo --region eu-west-2
    - name: Publish to s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp infrastructure/ec2-stack.template s3://s3artifactdemohemanth/demo/ --region eu-west-2
